### PR TITLE
OASP4J add NotFoundException to getTable on REST and WEB services

### PR DESCRIPTION
**Pull request by jhcore**
Fixing the issue https://github.com/oasp/oasp4j/issues/421

### CODE REVIEW

**Comment by hohwille** [comment]
This might be a minimal improvement but IMHO still the entire operation implementation is nuts:
* Why do we accept a String if all we want is a long and parse that ourselves? Simply change `(String id)` to `(long id)` and remove all the stupid error handling code.
* Why do we return null and put "business code" with a null-check and according exception into the service rather than just calling `find` instead of `findOne` here:
https://github.com/oasp/oasp4j/blob/develop/samples/core/src/main/java/io/oasp/gastronomy/restaurant/tablemanagement/logic/impl/TablemanagementImpl.java#L63

BTW: Please follow Java code guidelines and always use curly braces in control statements (like IF).

**Comment by jhcore** [comment]
Yes, the idea was follow the previous structure, this is much better but for some reason we had a string...I don't know

**Comment by maybeec** [comment]
Can we change the parameter to long in the PR? I would strongly recommend so rather than fixing bad code :)
Do small refactorings as often as possible rather than planning refactoring efforts as nobody will pay for this...

**Comment by jhcore** [comment]
ok I'm going to change it but I have a problem with this PR, maybe I need to open a new one

**Comment by jhcore** [comment]
New PR sorry for disturb https://github.com/oasp/oasp4j/pull/433

**Pull request closed without merging**
