### PR TITLE
#159: created drink state separation from OrderPosition

### PR DESCRIPTION
**Pull request by oelsabba**
Added a new field of drinkState within the  OrderPositionEto  to achieve a separate state for Drink. This is just the starting point of achieving the separation of SideDish and Meal too. A consequent modification in the UI is definitely needed

### CODE REVIEW

**Comment by hohwille** [comment]
Review:
Thanks for your pull request. Looks good now. However some feedback to improve:

1. @Column(name = "drink_state") - we are using camlCase for properties (e.g. modificationCounter). Only for foreign keys hibernate is implying "_id". See also https://github.com/oasp/oasp4j/wiki/guide-dataaccess-layer#database-migration
2. You created markOrderPositionDrinkAs method. That is consistent. However we should remove all these mark*As methods as they do not really make sense. We are changing the ETO and then call save on that.
3. The state verification is not yet correct as it verifies the drinkState and the orderPositionState separately. E.g. if the dinkState is ORDERED then the orderPositionState must NOT be advanced to DELIVERED or even PAYED. We need to add a Test-Case for the state changes as this is getting somewhat complicated.
4. You already extended OrderPositionSearchCriteriaTo accordingly, what is nice. To be consistent, you then also need to extend OrderPositionDaoImpl.findOrderPositions

**Comment by oelsabba** [comment]
@hohwille Thanks for your feedback. Regarding your comment , I need some clarification regarding points:

2. did you mean renaming markOrderPositionDrinkAs to e.g. saveOrderPositionState and deleting markOrderPositionAs? 
So that we can assure that updating the state of a Drink will result in updating the whole state of OrderPosition and there will be no ability of getting a sub-state updated without updating the whole OrderPositionState.  
3. did you mean that tests should be included within the scope of this issue? Or should a separte issue be created for testing?

Thanks.

**Comment by hohwille** [comment]
for 2- I was referring to deleting the methods mark*As entirely from the application as they are not used by the client and were never intended to be used. Somebody created the use-case method, someone else created REST services and for completeness he exposed all use-cases methods via Services and now you extrapolated to add further of such methods. This is an undesired but "viral" effect. So we should finally and entirely eliminate these methods.

for 3- in general I expect that when we develop new features we should implement module/developer test-cases as part of the job. If we want to keep this pull request simpler and want to have it merged earlier to avoid potential extra effort, feel free to create a separate issue for this.
However, we have already created a technical debt with our current low test coverage and we have to change in this area or we will never be able to come to a good and healthy state of tests.

**Comment by oelsabba** [comment]
@hohwille Thanks for your reply. I totally agree with you. To remain within the scope of this issue, I removed the mark*As methods that relate to this issue. However, we can file a new issue for removing all of them.

**Comment by hohwille** [comment]
@oelsabba perfect. this is the right way to go :+1:

**Comment by oelsabba** [comment]
@hohwille Thanks :satisfied:

**Comment by oelsabba** [comment]
@hohwille is there sth missing from my side regarding this pull request?

**Comment by hohwille** [comment]
@oelsabba we have some merge conflicts due to changes on the main repo develop line. However, the only delay is due to alignment with OASP4JS.

**Comment by hohwille** [comment]
We will merge this right after the release 1.1.0 is pulled out. However, I am on vacation next week. So it might take after easter if no one else does the merge...

**Comment by hohwille** [comment]
This one is overdue. Can someone do a final review and merge this? I currently have no time...

**Pull request merged**
