### PR TITLE
oasp/oasp4j#546: fixed the special characters issue in the template builder

### PR DESCRIPTION
**Pull request by antgauti**

### CODE REVIEW

**Comment by antgauti** [comment]
PR for issue #546 : OASP4J server code generator (v2.2+) failure caused by the '#' characters in the Java source code (see TestUtil.java line 27) which is included in a Velocity template.
@tbombail @sjimenez77

**Comment by kiran-vadla** [comment]
@antgauti and @sjimenez77 , fix has to be ideally pushed onto develop-2.3.0 branch and not develop branch.

Thanks,
Kiran.

**Comment by antgauti** [comment]
@kiran-vadla , this commit can be merged to `oasp:develop-2.3.0` (see my fork) so I just changed the base branch of this pull request. 
Do you need a new pull request ?

**Comment by kiran-vadla** [comment]
@antgauti , Thanks for changing the base branch to develop-2.3.0 . Now , the PR can be reviewed and merged .

**Comment by kiran-vadla** [comment]
@antgauti, I was testing your fix . As part of the testing , I have created sample application from the archetype generated . Sample application got created . I imported the sample application as a maven project in eclipse , built it and tried to launch the SpringBootApp . But , I receive an error and SpringBootApp is not launched . Attached is the stack trace. Please have a look. 

Thanks,
Kiran. 
[error.txt](https://github.com/oasp/oasp4j/files/844420/error.txt)

**Comment by antgauti** [comment]
@kiran-vadla, this is another issue, it's not related to my fix. 
See the stacktrace : 

> Missing column: userLogin in APP.PUBLIC.REVINFO

This error is caused by a database mapping problem : `userLogin` in class AdvancedRevisionEntity vs `user` column in table REVINFO (see /oasp4j/templates/server/src/main/resources/archetype-resources/core/src/main/resources/db/migration/h2/V0001__R001_Create_schema.sql).

**Comment by kiran-vadla** [comment]
@antgauti ,  I have analysed the issue more and found that h2 scripts in core\src\main\resources\db\migration\h2 in samples module are not getting copied to templates module. 

So , this issue is not related to your fix . I am going to create another issue for the above said issue. 

Thanks,
Kiran.

**Pull request merged**
