### PR TITLE
Added docs folder for gh pages and added oomph setups

### PR DESCRIPTION
**Pull request by themetalone**
Could someone also active gh pages based on the docs folder, please?

### CODE REVIEW

**Comment by kiran-vadla** [comment]
Hi @themetalone, 

Quick observation : 

1. I tried to access https://oasp.github.io/oasp4j in docs/README.md and received an error. 
2. If it is going to be part of next oasp4j release (oasp4j - 2.3.0),  you will have to change the base branch of the pull request . Please refer https://github.com/blog/2224-change-the-base-branch-of-a-pull-request to do the same. 

Also, Do we need to do some kind of testing as part of review of this PR ? 

Thanks,
@kiran-vadla

**Comment by themetalone** [comment]
Hello @kiran-vadla 
1. This is true since this address is only available if the gh pages based on the docs folder for this repository are activated. 
2. The files are not part of a release. They allow a fast and easy project setup via Eclipse Oomph.

Testing of the PR is not needed. The idea is, that the developers here take care of the file after the merge if the config isn't quite what's desired. I'll launch a Guide these days to describe how to work with those files.

**Comment by kiran-vadla** [comment]
Thanks @themetalone 

Will you please change the branch to 'develop-2.3.0' from master by following the link https://github.com/blog/2224-change-the-base-branch-of-a-pull-request . After that I will review and merge. 

Thanks,
@kiran-vadla

**Comment by maybeec** [comment]
@kiran-vadla gh-pages just work for the master branch. 
So no need to have it on the release branch.

**Pull request merged**
