### PR TITLE
#4: Added implementation of Orika bean mapper

### PR DESCRIPTION
**Pull request by oelsabba**
Please do NOT regard merging this branch right now. In this branch an implementation of the Orika bean mapper (http://orika-mapper.github.io/orika-docs/) is introduced. Moreover, a test case is added to verify bi-directional mapping using Orika.

I created a PR for that to have it reviewed/available as early as possible.

It is still missing JUnit parametrized tests that take as parameters both Orika and Dozer bean mappers together.

Looking forward for your review

### CODE REVIEW

**Comment by hohwille** [comment]
@oelsabba thanks for the contribution.
I have one suggestion for improvement: Can you extend the classes from the impl.dozer package with their original name in the original impl package but mark them as deprecated so we keep compatibility with our previous release (uses will have the classnames hardcoded in their config).
Ideally the deprecated classes have a log statement constructor that logs a warning about the deprecated usage and suggest to change to the new and correct package.

**Comment by oelsabba** [comment]
@hohwille

Thanks for your remark.
Based on the OASP logging guide: 

https://github.com/oasp/oasp4j/wiki/guide-logging

I considered the log level to be a warning. 

Morever, I added a simple Junit Paramaterized test for testing both running the same test using both Orika and Dozer. However,
I am totally not sure whether this is the implementation that you are targeting here:
> @oelsabba if you are looking for a way to run the same tests once with dozer and once with orika have a look here for how this can be done with JUnit:
 https://github.com/m-m-m/mmm/blob/master/mmm-client/mmm-client-ui/mmm-client-ui-widget/mmm-client-ui-widget-impl-test/src/test/java/net/sf/mmm/client/ui/impl/test/AbstractUiTest.java

Still there is a bit more to do. For example, I still need to try optimistic locking using Orika. See: https://github.com/oasp/oasp4j/issues/18

Again, feedback is appreciated :smile:

**Comment by oelsabba** [comment]
@hohwille Would appreciate if you take a look at the `OrikaDozerParametrizedTest.class`and tell me whether this is what you were targeting by parametrized tests?
Because I am not quite sure if I really got what you are aiming at.
Many thanks in advance. 

BTW: may be you would like to check: http://pragmatists.github.io/JUnitParams/

I am personally still not sure how promising is this approach in comparison to normal Parametrized JUnit tests.

**Comment by hohwille** [comment]
> Would appreciate if you take a look at the OrikaDozerParametrizedTest.classand tell me whether this is what you were targeting by parametrized tests?

Thanks for asking: You have mistaken exactly what was my suggestion. You should parameterize the technique which is dozer and orika instead of the tests. If you extract this to an abstract class that provides a method getBeanMapper() so that all @Test methods are run twice and the first run will receive a DozerMapper instance and the second run a OrikaMapper instance from getBeanMapper() you are at the point I intended.

**Comment by hohwille** [comment]
If you want to run business test logic for TableState.RESERVED and TableState.RESERVED simply add a parameterized private/protected method that you call from @Test methods with these two literals.

**Comment by hohwille** [comment]
We should soon integrate this into develop branch. But first we have to check what is wrong (travis, etc.).

**Comment by may-bee** [comment]
The cause of the failing builds seems to be the log-to-big issue again.
This issue has been solved in the host repository before the fork was created or the for introduces the debug logging again. We have to have a look at the merge diff to not introduce extensive logging again.

**Comment by hohwille** [comment]
Typically the best appraoch is to pull the changes from the oasp/oasp4j into the fork and merge there. Then close this PR and file a new one. If that is not possible, we will manually merge locally with care.

**Comment by hohwille** [comment]
We have already cherry picked relevant changes into oasp4j since a while ago.
What is left to do is to fix the problem how to convert from persistent entity to ETO honoring the modificationCounter that might get updated after conversion when TX is commited - this is not solved in this PR at all and is still open in OASP.
So I will close this PR and file a new issue for the remaining task.

**Comment by hohwille** [comment]
See #319

**Pull request closed without merging**
