### PR TITLE
Fixed: Proper usage of Test Categories in Sample pom.xml

### PR DESCRIPTION
**Pull request by jomora**
This PR fixes an issue that became obvious when debugging the restaurant sample app remotely.

No tests of type `SubsystemTest` were executed by Maven.

The problem was that the `pom.xml`of the sample project excluded by default not only `SystemTest`s but also  `SubsystemTests`.

Fixing the `pom.xml` and introducing different profiles which allow for execution of different supersets of test types solved the issue s.t. `SubsystemTest`s are now executed by default.

However, another problem arose after the fix:
Some Flyway migrations failed.

This problem was caused by the missing, but required, SQL scripts for batch tests in the subdirectory `src/test/resources/db/tablemanagement`.

Please review and merge!

### CODE REVIEW

**Comment by jomora** [comment]
@kiran-vadla, it would be awesome if you could provide more information in future comments, e.g. provide a link to the PR where the files have been introduced, *and* also state what your conclusion is, e.g. "close this PR" or whatever. This would help the reader to understand your comment more easily.

**Comment by kiran-vadla** [comment]
@jomora , You can refer to PRs #528, #527 , #526 . Files corresponding to V0003_R001_Add_blob_table.sql, V0004_R001_Add_batch_tables.sql for Oracle, MS SQL Server , PostGres and MariaDB have to be submitted . 

Thanks,
Kiran.

**Comment by jomora** [comment]
@kiran-vadla, in contrast to your comment, the files are currently not available in [*branch develop-2.3.0*](https://github.com/oasp/oasp4j/tree/eceff66509f506290025de30ec3fc3e0e02e2025/samples/core/src/test/resources/db/tablemanagement)(have a look at the current content of the branch).

So, two questions:
- Where are the files V0003_R001_Add_blob_table.sql, V0004_R001_Add_batch_tables.sql for Oracle , PostGres , mariaDB and MSSQL? I can't find them in the develop-2.3.0
- This PR contains V0003_R001_Add_blob_table.sql, V0004_R001_Add_batch_tables.sql for *H2 DB*. So, what should be changed from your point of view?

**Comment by kiran-vadla** [comment]
@jomora , since we have added these new files V0003_R001_Add_blob_table.sql and V0004_R001_Add_batch_tables.sql for H2 DB. Ideally similar files have to be added for databases PostGres, mariaDB , MSSQL and Oracle. 

Thanks, 
Kiran.

**Comment by jomora** [comment]
@kiran-vadla now I understand. You want me to add files which support the other DB vendors as well.

I propose to cover this in a separate pull request.

**Comment by kiran-vadla** [comment]
As discussed with @jomora , another PR will be created to address other Databases . Hence approving this PR.

**Pull request merged**
