### PR TITLE
Lines with @author tags removed (issue #455) 

### PR DESCRIPTION
**Pull request by SimonHuber**
All lines containing '@author' removed using the regex ' \* @author.*\r\n'

### CODE REVIEW

**Comment by SimonHuber** [comment]
In Eclipse you can prevent the author tag in new java files by applying the Code Templates. To do so go to Window->Preferences...
eclipse_codetemplates

**Comment by SimonHuber** [comment]
If you have merge conflicts like this:

author


Using the following regex in eclipse helps to delete these lines and thus resolve merge conflicts:

<* HEAD.\*\r\n.\*\@author.\*\r\n.\*\r\n>\*.\*\r\n

**Comment by sroeger** [comment]
The next version of oasp-ide comes pre configured with this change to prevent the generation of the @author tags.

**Comment by hohwille** [comment]
:+1: Thanks

**Pull request merged**
