### PR TITLE
 #470: Upgrade to Spring Boot 1.3.8.RELEASE

### PR DESCRIPTION
**Pull request by sobkowiak**

### CODE REVIEW

**Comment by hohwille** [comment]
I would like to merge. Any concerns for 2.1.2 releas? Wait for 2.2.0?

**Comment by jomora** [comment]
As this is not a bug, I'm not sure whether this belongs to a bug-fix release - except the release is more than a bug-fix release :-)

**Comment by kiran-vadla** [comment]
@sobkowiak , @hohwille , Can any one of you look into this pull request please ?

**Comment by sobkowiak** [comment]
PR merged into branch develop-2.2.0

**Pull request closed without merging**
