### PR TITLE
Adding abstract persistence application entity

### PR DESCRIPTION
**Pull request by jhcore**
OASP4J Sample Application:

- Create the class AbstractPersistenceApplicationEntity (copy of the deprecate class AbstractPersistenceEntity)

- Do the class AbstractPersistenceEntity of the module jpa as deprecated

- Now the class ApplicationPersistenceEntity extends a the new class called  AbstractPersistenceApplicationEntity (customization of the class AbstractPersistenceEntity)

### CODE REVIEW

**Comment by jhcore** [comment]
Can someone verify this patch?. If you can do it  today, it would be great!

**Comment by hohwille** [comment]
Why don't we just put the entity code into the existing `ApplicationPersistenceEntity`?
That was intended as a minimal shim to the `AbstractPersistenceEntity` for decouplings like the current case.

**Comment by hohwille** [comment]
Further we should change the now deprecated `AbstractPersistenceEntity` back to its original state with generator type sequence because we did not want to break compatibility.

**Comment by hohwille** [comment]
Sorry, if I missed this but I can not guarantee to give a review within one day. I am working in a customer project that of course has priority so I can only help out here when there is time left...

**Pull request merged**
