### PR TITLE
OASP Sample -> adding @Ignore some conflicted tests

### PR DESCRIPTION
**Pull request by jhcore**
Stable version of OASP4J.

### CODE REVIEW

**Comment by hohwille** [comment]
What is the actual conflict as travis is passing? Is there any link to an error (stacktrace, surefure-report, etc.)? Or could this only be a problem of your local code base or machine setup?

**Comment by jhcore** [comment]
Is not an error, is a failed test because if you run the test with maven you are modifying the data base with a batch task, but later, you need to check the previous data, if you run the test separately you get success because the before test doesn't modify the data base. Maybe we can do a @After and @Before to solved this.

**Comment by jhcore** [comment]
Can one of the admins verify this patch?

**Comment by jhcore** [comment]
We need to confirm this because is the stable version to Devonfw 2.1.0

**Comment by hohwille** [comment]
I assume the tests are already fixed by #430

**Comment by jomora** [comment]
@hohwille, @jhcore As #430 has been accepted including a proper solution of this problem, we should revert this PR. Do you agree?

**Comment by jhcore** [comment]
@jomora yes, sorry I forgot to close this PR

**Pull request closed without merging**
