### PR TITLE
#193: a simple offset based paging support 

### PR DESCRIPTION
**Pull request by llaszkie**
Server side and through REST-GET available. I will switch to oasp4js client app to provide a sample usage.

### CODE REVIEW

**Comment by hohwille** [comment]
@llaszkie thanks for your PR. Looks good in general. Can you check why the merge fails?
I would suggest to couple RequestParameters and PagingParameters the other way round (so the PagingParameters contain the logic how to map to request parameters) as RequestParameters is a very generic class. 
Further, I still think the paramters actually need to go into the SearchCriteriaTo itself. E.g. if we want to post the data as JSON instead this would not work.
So finally my suggestion would be to drop PagingParameters and add the page Parameter to AbstractSearchCriteria/SearchCriteriaTo (create a class in oasp4j-jpa and decouple from mmm as suggested by @amarinso, then we need an additional method applyCriteria in our DAO).
What do you think?

**Comment by llaszkie** [comment]
Regarding build: mater is also failing, so it is not the merge issue (see build#152).
Regarding review: I agree: it is good idea to reverse the relation RequestParameters -> PagingParameters 
Regarding sugestion: I will try to redesign SearchCriteria a bit as suggested. Let's see in the next comming commit if it improved the solution :-)

**Comment by hohwille** [comment]
> Regarding build: master is also failing, so it is not the merge issue (see build#152).

Right. But when I do a fresh clone of oasp4j.git and then run ```mvn install``` runs fine. Also jenkins ci job is successful. I do not understand what is going on in travis. Unfortunately I can not get any more details than the maven log from travis.

**Comment by henning-cg** [comment]
@llaszkie: Are you still working on this feature? I am asking because we need support for this in order to properly define the metadata protocol.

Regards,

Henning

**Comment by hohwille** [comment]
Unfortunately we did not yet make it and will miss 1.2.0. We should clarify responsibility and ensure that we can get this done for 1.3.0... Thanks so far to all contributors for their work. I think the concept is quite clear. We can also decouple the base class for search criteria from mmm as suggested by @amarinso and have the freedom to implement the current proposal of the meta-data concept for pagination that we have disucssed.

**Comment by hohwille** [comment]
As we now have paging support integrated from another and complete pull-request, I will now close this one. IMHO the other PR was influenced by your work. Thanks for supporting paging. It will be included in the next release 1.3.0.

**Pull request closed without merging**
