### PR TITLE
Request execution time

### PR DESCRIPTION
**Pull request by trippl**
Added the PerformanceLogFilter.java class to measure execution time of each request.

### CODE REVIEW

**Comment by maihacke** [comment]
Was ist wenn die doFilterMethode eine Exception wirft. Dann fehlt der Log-Eintrag. Sollte das nicht über ein try/finally abgebildet werden, um auf jeden Fall zu loggen?

**Comment by trippl** [comment]
Da hast du recht. Ich habe es angepasst. Hattest du dir das so gedacht?

**Comment by hohwille** [comment]
I think this needs to be verified by an example. In case or our REST-Services we however have a facade that is already handling all exceptions so they will never reach your filter and all is fine (even without the change). But you should add a simple servlet that always throws an exception for testing and then check what is logged.
Putting the filter into oasp4j-logging makes perfectly sense to me also the Naming. If that is tested with an exception and works as expected I would consider this complete and we should merge it.

**Comment by hohwille** [comment]
BTW: so far I am not sure that getStatus will return a correct result if the exception has not yet been handled. In that case the code must not be in finally block but you need two cases: One after doChain inside the try and one inside a catch(Throwable) block that is logging and then re-throwing the catched exception.

**Comment by hohwille** [comment]
The Travis build failure seems not be related to your PR and has been fixed in OASP meanwhile. If you do the little update (see previous comment) everything should be fine. Thanks!

**Pull request merged**
