### PR TITLE
#232: migration to spring-boot

### PR DESCRIPTION
**Pull request by hohwille**
spring-boot version of OASP4J is ready to be merged.

### CODE REVIEW

**Comment by hohwille** [comment]
Tests all pass. Looks good.
Any concerns? I will merge soon...

**Comment by sobkowiak** [comment]
Looks good for me :+1:

**Comment by amarinso** [comment]
I find missing my two PR on the oasp-forge repository

6# Enable CORS preflight request 

4# Force locale to en_EN in order to make the tests pass

But of course they can be done later if you prefer

**Comment by hohwille** [comment]
@amarinso: Thanks for your feedback.
Indeed something went wrong here:
https://github.com/oasp-forge/oasp4j-spring-boot/pulls

I merged one of them that was obvious.

@MarcoRose could you take care of this one:
https://github.com/oasp-forge/oasp4j-spring-boot/pull/6

@amarinso would it be possible if you do a forward merge for PR6 so it can be merged automatically and we can see if travis is green?

**Comment by amarinso** [comment]
@hohwille I've redone the PR on top of the develop branch

**Comment by MarcoRose** [comment]
Great Job, well done

**Pull request merged**
