### PR TITLE
Offermanagement refactored to use case pattern

### PR DESCRIPTION
**Pull request by may-bee**
As discussed in oasp/oasp4j#219 with @amarinso , I refactored the offermanagement again to the use case pattern as the offermanagement is sufficiently complex to not be implemented in the component interface completely.

### CODE REVIEW

**Comment by amarinso** [comment]
Well, I think that what was agreed on was to keep `SalesManagement` with the UseCase pattern and everything else on the more simple approach.

Maybe the best approach is to have a chapter on the tutorial explaining the sample application, what is showcasing and what an application could re-use.

Also I see that the PR includes a modification of the pom.xml file that should go in my opinion in another PR (or not? I'm in doubt in how to operate changes that are cross to other concerns)

**Comment by amarinso** [comment]
@may-bee I correct myself, I missed the previous PR that included the updated version :-)

**Comment by may-bee** [comment]
There is also some work to do as I see the travis build fails. I will work on that soon.

**Comment by hohwille** [comment]
Can we merge this? What is the status here?

**Comment by may-bee** [comment]
We can merge this from my side if it is ok for @amarinso .

**Comment by amarinso** [comment]
@may-bee for me is ok, but we still need to explain somewhere in the documentation why are we mixing different approaches on the restaurant application.

I've already started such page:

https://github.com/oasp-forge/oasp4j-wiki/wiki/tutorial-sample

we can add more content explaining what's providing the sample application.

**Comment by MarcoRose** [comment]
resolved

**Pull request closed without merging**
