### PR TITLE
 #469: Upgrade to Apache CXF 3.1.8

### PR DESCRIPTION
**Pull request by sobkowiak**

### CODE REVIEW

**Comment by hohwille** [comment]
I would like to merge. Any concerns for 2.1.2 releas? Wait for 2.2.0?

**Comment by jomora** [comment]
As this is not a bug, I'm not sure whether this belongs to a bug-fix release - except the release is more than a bug-fix release :-) If so, we should add the according label.

**Comment by kiran-vadla** [comment]
@sobkowiak , Just to remind on this PR.

**Comment by sobkowiak** [comment]
PR merged into branch develop-2.2.0

**Pull request closed without merging**
