### PR TITLE
NPE fixes + retrieve raw picture service added

### PR DESCRIPTION
**Pull request by may-bee**
The raw picture service has been added temporarily for working with it on a project at the university. There might be additional requirements and results of the disucssion of #304, which might influence this pull request or the services further.

### CODE REVIEW

**Comment by hohwille** [comment]
Review:
* Adding an <Entity>NotFoundException for each entity seems pointless to me. Be aware that we could also reuse the exisitng ObjectNotFoundUserException that is generic for any entity/object.
* We still need to find a solution to prevent reading the BLOB into memory.

Anyways thanks for the fix. As it is currently worse, I would even not mind merging this as is. Can you comment if you would do some rework? Otherwiese I would merge as is and we can still improve afterwards...

**Comment by may-bee** [comment]
I will at least fix the issue with the exception. I had done some research regarding the other issue. Streaming a blob from database to the service client is not that problematic, but streaming contents from the service client directly to database seems to not have a valid solution. There are different solutions creating a blob from an inputstream, but they depend on heuristics implemented in the Java API trying to calculate the length of the inputstream without reading it entirely. Unfortunately, the length of the binary data is mandatory for creating a blob.

**Comment by hohwille** [comment]
Fine. Thanks for the feedback. We have to discuss if handling BLOBs in transaction DB is still state-of-the-art as this is also a matter of performance and through-put where RDBMS are rather poor. As an intermediate solution it is still possible to stream the BLOB to the temp-dir and then deliver from there. However, we will first merge the fix using a byte[] even though it is more of an anti-pattern.

**Comment by may-bee** [comment]
done.

**Comment by hohwille** [comment]
Thanks!

**Pull request merged**
