### PR TITLE
Code cleanup / adding JavaDoc

### PR DESCRIPTION
**Pull request by sroeger**
This PR does several changes demanded in #392. This includes
- resolving / creating issues concerning code markers TODO and REVIEW
  - added a default status for PaymentStatus 
  - added check for sidedishState and mealState (this includes some minor changes in the sql script and related entity/eto)
  - added test for not allowed change of a ProductOrderState in SalesManagementTest
- adds JavaDocs (also for CobiGen generated test data builders - I created a PR so these builders will include JavaDoc automatically)
- formatting was done automatically

### CODE REVIEW

**Comment by hohwille** [comment]
Can someone resolve the conflicts?

**Comment by kiran-vadla** [comment]
@jomora , Just to remind on this PR.

**Comment by kiran-vadla** [comment]
I have reviewed and merged this pull request.

**Comment by hohwille** [comment]
Funny. It seems that this PR was actually not merged but simply closed. I just redid the same changes again. Sad waste...

**Comment by hohwille** [comment]
See PR #629

**Pull request closed without merging**
