### PR TITLE
Improved Test Data Infrastructure 

### PR DESCRIPTION
**Pull request by jomora**
Changed `io.oasp.gastronomy.restaurant.general.common.RestraurantTestHelper`, `io.oasp.gastronomy.restaurant.tablemanagement.service.impl.rest.TablemanagementRestServiceWebIntegrationTest` and `io.oasp.gastronomy.restaurant.general.common.base.RestaurantWebIntegrationSubsystemTest` to support proper handling of test data by leveraging features offered by Flyway. This test infrastructure allows to reset the database according to a specified baseline and migration version (possibly defined per test class using `@TestPropertySource` annotation, or for all tests by default via `application.properties`).
To disable default migrations aimed at production environments during the tests, set `database.migration.auto=false`. This helps to avoid Flyway validation errors. 

In addition, a bug in `PaginatedListTo` and `PaginatedResultTo` was resolved. Both were missing a default constructor which resulted in `com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type`, e.g. when calling `PaginatedListTo<TableEto> findTablesByPost(TableSearchCriteriaTo searchCriteriaTo)` in `TablemanagementRestService`.

@hohwille, could you review the changes, please?

Thank you very much in advance!

Cheers!

### CODE REVIEW

**Comment by hohwille** [comment]
BTW: Could we also rename some classes. The prefix `Restaurant` should not be used for totally generic code that might later move to `oasp4j-module-test`. What is restaurant specific about `RestaurantTestHelper` - nothing.
IMHO we should instead create small beans and call them `DbTestHelper`, `SecurityTestHelper,` etc.
So the login/logout stuff would go to `SecurityTestHelper,` and the flyway stuff to `DbTestHelper`. You should not aim to write a wrapper for flyway with all its features. Then one can also just inject flyway and use it directly. I think we should have operations like `resetDatabase()` that does the clean followed by a migration.

**Comment by hohwille** [comment]
For the naming I if test-classes, I would suggest to introduce short but meaningful names and according conventions added to the documentation (testing guide):
* XRestServiceTest
* XDaoTest
* XUcTest
And for the infrastructure we provide abstract test classes where `X` is `Abstract` while the actual tests then use the object under test (e.g. `TablemanagementRestServiceTest`).

**Comment by hohwille** [comment]
What is that `client` module in the diff and why is there a `web.xml` in your PR? Merge failure? I have also seen that in a different PR and are slightly confused what is going on here...

**Comment by jomora** [comment]
@hohwille You're definitely right! The merge went wrong. I propose to handle this problem by reverting the [current PR](https://help.github.com/articles/reverting-a-pull-request), and then reverting the changes locally before filing a new PR.
Do you agree or do you see another option?

**Comment by hohwille** [comment]
@jomora can you have a look at #426 would that be fixed with this PR?

**Comment by jomora** [comment]
@hohwille , @jhcore please have a look at [47d2d2a](https://github.com/oasp/oasp4j/pull/430/commits/47d2d2af656214134324e80a841e0c99606d2879) w.r.t . #426. Fixed the test s.t. the database is reset before test execution. This omitts the usage of `@Ignore`.

**Pull request merged**
