### PR TITLE
implement issue 290

### PR DESCRIPTION
**Pull request by amarinso**

### CODE REVIEW

**Comment by hohwille** [comment]
Thanks. Looks good but I have some questions:
* You are introducing java packaging for resources (io/oasp/logging) here. Should we actually do that? Maybe in this case it is a good idea but so far we used just classpaths like config/app and config/env for general resources. An an alternative would be ```config/app/logging```.
* Actually the log-pattern is something specific here. Should we really have it externalized into our properties? I would rather put it directly in ```base.xml```.

**Comment by hohwille** [comment]
I like this change and would love to see it in the next release.
However, I want to do some testing and minimal rework.
Especially we need to test if we can override the logback.xml with an external file (e.g. via spring-boot ```application.xml```) and from there have include tags on resources from classpath. If that is working the solution is perfect. If that is causing trouble, we should first find a solution.

**Comment by hohwille** [comment]
I also think that importing ```application.properties``` is technically not a good idea here (even though I like the idea of having appname in one place also for the spring application). This will also cause trouble when we update to spring boot. I would suggest that properties that can be defined by end-users of OASP should be defined direcly in their ```logback.xml``` or they should import their ```application.properties``` themselves.

**Comment by amarinso** [comment]
Can you specify a bit more why is this not a good idea technically? which problems do you foresee?

In my opinion properties that end-users have to define/change should be grouped together in a single file to make their life easier and we should provide a way to distribute those values to proper places.

**Comment by amarinso** [comment]
Maybe we can have more uniform file names for intended user-modificable settings, I mean if we have **application.properties** and **application-default.properties", for log files instead of having simply **properties.xml** it could be **application-log.properties.xml**

Thus is not the same file but naming makes them more "related"

**Comment by hohwille** [comment]
replaced by #314

**Pull request closed without merging**
