### PR TITLE
Excluded third party libraries that are not needed from sample application

### PR DESCRIPTION
**Pull request by kiran-vadla**
Fix for the issue #567 is provided as part of this PR . @amarinso , I  did the minor changes w.r.t to removing the commented code and line spaces that you have mentioned in PR#570 and submitting a new PR. Regarding excluding spring-boot-stater-tomcat from base archetype and sample application , I have created a maven profile as follows in sample/core/pom.xml and tried . But it didnot work . Whether , we activate it or de-activate it , we will have spring-boot-starter-web available as part of the WEB-INF/lib of the war file . I have tried placing this profile in samples/server/pom.xml as well but in vain. 

I noticed that for this issue of excluding embedded tomcat , already instructions are provided at https://github.com/devonfw/devon-guide/wiki/getting-started-deployment-on-tomcat under section 'Deploy on Tomcat' as points 1 and 2 . So, I believe extra instructions will be redundant. Please review this PR as soon as possible and let me know. 

----------------------
Maven Profile
----------------------
    <profile>
      <id>spring-boot-tomcat</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <dependencies>
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
      </dependencies>
    </profile>
----------------------

Thanks,
@kiran-vadla

### CODE REVIEW

**Comment by amarinso** [comment]
If we provide the profiles, the instructions will be redundant... or better they will have to be rewritten

I've tried with success the following:
----------------------
oasp4j/pom.xml
----------------------
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
            <exclusion>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-tomcat</artifactId>
            </exclusion>
       </exclusions>
    </dependency>
    <profiles>
    ....
    ....
    <profile>
      <id>embedded</id>
        <activation>
         <activeByDefault>true</activeByDefault>
        </activation>
      <dependencies>
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId> 
        </dependency>
      </dependencies>
    </profile>
  </profiles>
----------------------

So now, you can compile with two options:

- with embedded tomcat, the *embedded* profile is active by default
`mvn clean install -Dmaven.test.skip=true`

- for an external Tomcat deployment, deactivate the *embedded* profile on the command line
`mvn clean install -Dmaven.test.skip=true -P !embedded`

**Comment by amarinso** [comment]
I've tested removing the `spring-boot-starter-jdbc` dependency on the core/pom.xml and now the WAR generated with `-P !embedded` contains no jar from tomcat.

As far as I know, the `spring-boot-starter-jdbc` is meant to be used when jdbcTemplate is required (https://spring.io/guides/gs/relational-data-access/) and thus we don't really need it neither on the sample application nor the archetype.

**Comment by kiran-vadla** [comment]
Hi @amarinso . Thanks for providing detailed feedback . spring-boot-starter-jdbc is already removed . I have submitted the changes pertaining to the introduction of new profile and exclusion of spring-boot-starter-validation from spring-boot-starter-web and tested it . Please review the same . 

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment]
@amarinso , Will update the wiki for switching between embedded and external tomcat profiles once the PR is approved . 

Thanks,
@kiran-vadla

**Comment by amarinso** [comment]
I don't understand why the "changed files" tab shows the modification for WebConfig.java for the CharacterEncodingFilter issue...

If that change is alredy on oasp-2.4.0 branch... why is showing in the diff??

**Comment by kiran-vadla** [comment]
Hi @amarinso , Please review it now .  

Thanks,
Kiran.

**Pull request merged**
