### PR TITLE
#290: improved PR from amarinso

### PR DESCRIPTION
**Pull request by hohwille**
I did little improvements to the PR from @amarinso 
* removed inclusion of ```application.properties```
* modularized appenders (e.g. if someone wants to use only error or all except debug)
* improved properties and renamed provided XML configs
* renamed ```filePath``` to ```logPath```
* tidy up (stop discussions in XML comments)
* remove relaoding from test logging config (makes no sense)

Main effort was the testing with various scenarios:
* loading ```logback.xml``` from file with inclusions of files on classpath: works
* spring-boot scenarios: works
* spring classic usage (current OASP): works
* property overriding: works only partial

For the last point some explanation:
This is actually a limitation of logback. You can override properties from included XMLs but if the XML defines properties that use other properties from the same included file that can not be overridden from outside.
An example:
```
<included>
  <property name="appname" value="defaultApp"/>
  <property name="logPath" value="logs"/>
  <property name="errorLogFile" value="${logPath}/error_log_${HOSTNAME}_${appname}"/>
</included>
```
In such case you can not override ```logPath``` or ```appname``` outside the include without also overriding ```errorLogFile```. For this reason I did not include ```logPath``` in that place but in the appenders in all places and also did not define a default for ```appname```.

### CODE REVIEW

**Comment by amarinso** [comment]
Sorry Jörg , I think I looked directly the code changes and missed your comments and explanation.

I commented on #293 that maybe the file names for properties could be aligned, so it could be `application-log.properties.xml`  or `application-default-log.properties.xml`

I'm aware that the names get horribly long...

**Comment by hohwille** [comment]
Thanks @amarinso for your feedback.
If I understand correctly you are proposing to use ```*.properties``` instead of ```*.xml``` for the properties what makes perfectly sense. However, I was already discussion in your PR about the namespacing:
* Either we keep the logging setup in ```io/oasp/logging/logback``` as you did initally. Then I would propose to also keep the properties there. We can name them ```application-log.properties``` as suggested (```properties.properties``` instead of ```properties.xml``` would not make much sense anyway).
* Or we move everything to a less "political" package like ```conf/app```.

I decided to go for your initial approach esp. after spring boot will make us rename the ```conf``` to ```config``` and eleminate ```app``` and ```env``` anyway. I also suppose that spring-boot is already a stronger "standard" than what we defined and it is fine to follow that. We should not mix the logging setup into this field to keep things simple and independent.

**Comment by hohwille** [comment]
To summarize up:
* I would rename ```properties.xml``` to ```application-log.properties``` and convert it from XML to properties format.

Eveything else is now clear. 
OK?

**Comment by hohwille** [comment]
FYI: Spring-Boot is quite flexible in configuration and we will not be able and probably even do not want to "reimplement" this for logback. However, users would expect this behaviour if we mix the logging properties into the regular configuration:
http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Pull request merged**
