### PR TITLE
Removed inherit doc comments in overrided methods #251

### PR DESCRIPTION
**Pull request by dsanche2**
Removed inherit doc comments in overrided methods #251

### CODE REVIEW

**Comment by hohwille** [comment]
@dsanche2 thanks for the PR. Nice and big cleanup.
I found one issue:
```GenericRevisionedDao``` there you also removed ```{@inheritDoc}``` for delete what is actually IMHO still required as otherwise the parent methods javadoc is then replaced instead of extended.

**Comment by hohwille** [comment]
Did I also update the code-template from ```<code>```  to ```{@code}```? I have to check in oasp4j-ide.

**Comment by dsanche2** [comment]
`GenericRevisionedDao` was my mistake. I`m going to fix it and thel I will do a PR.

I have changed all `<code>` by `{@code}` without check if you had updated in oasp4-ide, I thought you had done the change, in addition, I don´t know where you configure this settings.

What should I do now?

**Comment by hohwille** [comment]
> What should I do now?

I have updated the templates/settings.

**Comment by hohwille** [comment]
BTW: If someone is interested how to modify these eclipse settings.
https://github.com/oasp/oasp4j-ide/wiki/guide-settings#eclipse-settings
Simply change the settings in Eclipse Preferences, shut down eclipse an run ```scripts/update-eclipse-workspace-settings```. Then you review the diffs and commit the changes. Others can pull the changes and run ```update-all-workspaces``` and all workspaces have the new settings.

**Comment by hohwille** [comment]
All complete including GenericRevisionedDao - thanks for your help.

**Pull request merged**
