### PR TITLE
#339:fixed

### PR DESCRIPTION
**Pull request by sesslinger**
added NotNull annotation

### CODE REVIEW

**Comment by hohwille** [comment]
Technically correct - solves the issue.
Validation guide is still incomplete here but IMHO constraints should be annotated in the getter of the interface. Therefore validation can happen early one (when use-case is invoked). The earlier the validation the better.
I assume the current code is not consistent in the area at all. We can also create a separate ticket for my concern here and first merge this one.
WDYT?

**Comment by sesslinger** [comment]
As far as I could see, whenever we use @NotNull it's annotated in the getter, so I moved the annotation there.

**Comment by hohwille** [comment]
> Validation guide is still incomplete here but IMHO constraints should be annotated in the getter of the interface.

Sorry for bugging you but can you move it to the getter on the interface so it also applies to the ETO? Can you test that it is still working then. We should then also update the validation guide for this aspect (or create an issue for that). Thanks!

**Comment by sesslinger** [comment]
The method `getOrder()`is not declared in the interface `OrderPosition`. `getOrderId()`, which is declared there, already has a `@NotNull` annotation.

**Comment by hohwille** [comment]
Thanks for the explanation. I did not see that. Then we would also need @NotNull for getOrderId() in the interface to validate the OrderEto, right?

**Comment by sesslinger** [comment]
getOrderId() already has the @NotNull. So I am not sure, if this pull request will fix #339. I tried to reproduce the behaviour (`SalesManagement.saveOrderPosition(OrderPositionEto)`) I always got a ConstraintViolationException due to the exisiting @NotNull for getOrderId().

**Comment by hohwille** [comment]
Thanks, I will merge this and comment #339.

**Pull request merged**
