### PR TITLE
 replace Criteria API with dynamic queries using QueryDSL #220 

### PR DESCRIPTION
**Pull request by cmammado**
I replaced Criteria API in io.oasp.gastronomy.restaurant.offermanagement.dataaccess.impl.dao.OfferDaoImpl with QueryDSL. Looking forward for a feedback

### CODE REVIEW

**Comment by maihacke** [comment]
Sorry, I have very limited time at the moment. So I had just a short look on the changes.
Two points came to my attention

1. Why is there a change in the maven-ant-plugin-version?
2. For me it looks like this PR introduces query dsl-codegeneration. OASP recommendation is to not use the code generation. Why is this changed?

**Comment by amarinso** [comment]
I don't have actual experience in QueryDSL but reading the files changed I think that we could benefit from the recommended use of `static import` on the [the documentation] of QueryDSL (http://www.querydsl.com/static/querydsl/2.1.0/reference/html/ch02s03.html) to reduce clutter

` import static com.mysema.query.alias.Alias.$;`

**Comment by amarinso** [comment]
Also curious about @maihacke comment, I think that if we don't use "generated query types" then we don't need the code generation

**Comment by nelooo** [comment]
The main advantage of QueryDSL generated objects are the type safe queries. The generated "QObjects" allow you to create type safe queries, simplifying error detection, in compilation time,  in database model changes.  

Also the generated types allow you to create custom methods to access database, simplifying the the creation of portable solutions around different databases of functional queries like phonetic sound search, that will be included in all generated objects of some type. 

http://www.querydsl.com/static/querydsl/2.1.0/reference/html/ch03s02.html

IMHO is a good idea to use the generated code in QueryDSL.

**Comment by maihacke** [comment]
The point is that querydsl offers typesafe queries without code generation. This is a big advantage, since those generation processes often lead to problems in the long-term.
I must admit that I did not fully understand what those delegate methods are for. If we need custom query methods, we will put them in the corresponding dao.
Btw I think this is not the place to discuss if we should introduce code generation for querydsl. I think we should not, but if somebody wants to change that discussion he may create a separate ticket for that.

**Comment by nelooo** [comment]
Ok, I didn't know QueryDSL capability of typesafe queries without code generation. 

Custom methods also can be used without code generation, so it's not needed.

**Pull request closed without merging**
