### PR TITLE
Changed rest exception response format for validation errors.

### PR DESCRIPTION
**Pull request by dsanche2**
We now list every validation error for each attribute individually, so it can be parsed on the client side.
Validation format example:
{
  "message": "validation message",
  "code": "validation code",
  "uuid":generated uuid,
  "errors" : {
     "fieldname1" : [
         "message1",
         "message2"
     ],
     "fieldname2" : [
         "message3"
     ]
  }
}
 
In addition, I have added a test for Constraints Validation Exceptions. I needed to add hibernate libraries to pom.xml (as test scope) because it was neccesary a provider for validation. I guess you didn´t do it because you didn´t want to add dependencies with hibernate to the rest module. If you consider it´s wrong, let me know.

### CODE REVIEW

**Comment by hohwille** [comment]
Thanks for the PR.
:+1: on the general change. I have not merged locally and debugged but from the diff it looks good.

Review feedback on POM change:
* why do we need dependency on org.glassfish.web:javax.el? I think we do not need that and shall omit it.
* we should put the el version into a variable of oasp4j-bom and declare it via dependency management.

**Comment by dsanche2** [comment]
We need dependency "org.glassfish.web:javax.el" because is the implementation of the "javax.el-api" dependency. If you don´t include that depedency you´ll get an exception.

Respecting to put the el version into a variable, ok, my fault, I don´t know oaspj4-bom was the correct place.

**Comment by hohwille** [comment]
spring exploded again in travis:

> Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'ucManageTableImpl': Bean with name 'ucManageTableImpl' has been injected into other beans [tablemanagementImpl] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesOfType' with the 'allowEagerInit' flag turned off, for example.

I do not see how this relates to the changes of this PR. I also do not see that changing auto-wiring to "byName" was the right choice:
https://github.com/oasp/oasp4j/commit/0b5ecafda5933731d22c96324bec9dbe503c55c0
We need some more investigation on what is going wrong with travis currently travis is causing more headaches than being of help. That is sad...

**Comment by hohwille** [comment]
> We need dependency "org.glassfish.web:javax.el" because is the implementation of the "javax.el-api" dependency.

Did you verify that? What do you need el for? IMHO for hibernate-validator. Then the el API is IMHO sufficient. Please try it first by removing the glassfish dep and test the code.

**Comment by may-bee** [comment]
> I do not see how this relates to the changes of this PR. I also do not see that changing auto-wiring to "byName" was the right choice.

The problem is the circular dependency between component interface and the components use cases. So the easiest and most compliant fix will be reimplementing the component interface rather than letting the component interface inherit all use case interfaces. Nevertheless, this also introduces redundancy.

Also a valid fix might be explicitly declarating the injection in a spring bean configuration (e.g. xml, which we thrown away for OASP).

I will try to prioritize the use case beans to resolve the circular dependency in this special case.

**Comment by may-bee** [comment]
Is this pull request finished so far? No Open Issues / Reviewed?
Then we might want to merge it, that I can get travis working again as I cannot commit to @dsanche2 repository to work on this pull request.

**Comment by dsanche2** [comment]
Yes @hohwille, we need el dependency for hibernate validations to testing constraint validations exceptions. If you don´t use the implementation (org.glassfish.web:javax.el) you get an exception: javax.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found. So I searched about this error and I found a solution in stactoverflow: http://stackoverflow.com/questions/19451814/java-lang-noclassdeffounderror-javax-el-propertynotfoundexception-when-i-send-i 

I didn´t find a better solution.

**Comment by may-bee** [comment]
build issue seems to be fixed

**Comment by hohwille** [comment]
Thanks to everybody and especially to @dsanche2 for the PR.

**Pull request merged**
