### PR TITLE
#230 avoid redundant version numbers in POMs

### PR DESCRIPTION
**Pull request by amarinso**
I've moved 
`oasp4j/oasp4j-templates/oasp4j-template-server/src/main/templates/archetype-resources/pom.xml`
to:
`oasp4j/oasp4j-templates/oasp4j-template-server/src/main/resources/pom.xml`

and then added filtering for resources on the `oasp4j/oasp4j-templates/oasp4j-template-server/pom.xml`

I've added the properties :

- `spring.boot.version`
- `java.version`

Have you identified more variables to change?

### CODE REVIEW

**Comment by hohwille** [comment]
Archetype fails with this error
> java.lang.IllegalArgumentException: invalid target release: 1.7.0_76

Seems to be the javac target level. Why is it not 1.7 but 1.7.0_76? How does this relate to the changes of this PR? Travis confuses me...

**Comment by hohwille** [comment]
Do you use Eclipse for formatting? Your XML indent does not match according to the diffs I see here on the web-view (may be even tabs). No real problem but nice if we all follow the same style and use eclipse formatter for that.

**Comment by hohwille** [comment]
In general your PR looks good to me :+1: 
We have to understand what is actually the problem of the build error. I can see it right away...

**Comment by sobkowiak** [comment]
> Seems to be the javac target level. Why is it not 1.7 but 1.7.0_76? How does this relate to the changes of this PR? Travis confuses me...

The `java.version` is a Java system property resolved to JRE version number. It means, following code
 ```xml
<java.version>^java.version^</java.version>
```

resolves to

```xml
<java.version>1.7.0_76</java.version>
```

We should define own variables in the main pom file and use them in the `maven-compiler-plugin` in main pom and in template. Something like this:

```xml
<maven.compiler.source>1.7</maven.compiler.source><maven.compiler.target>1.7</maven.compiler.target>
```

in template

```xml
<maven.compiler.source>^maven.compiler.source^</maven.compiler.source><maven.compiler.target>^maven.compiler.target^</maven.compiler.target>
```

and in compiler plugin:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
      <encoding>${project.build.sourceEncoding}</encoding>
      <source>${maven.compiler.source}</source>
      <target>${maven.compiler.target}</target>
    </configuration>
</plugin>
```

**Comment by sobkowiak** [comment]
I'm going to apply this pr and correct it

**Comment by hohwille** [comment]
Both spring BOM and OASP and most other maven projects I know just use a variable called ```java.version``` in the POM. However, this is also a predefined system property of the JVM:
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

That seems to cause the problem when resolving ```${java.version}``` here as in our case the JVM system property value was resolved from some reason that is the exact JVM java version including minor and update level. This however is not accepted by javac.

Anyhow it seems pointless to separate ```maven.compiler.source``` and ```maven.compiler.target``` as it will never work properly if they are different. This was invented in javac with the idea in mind that you could compile new syntax to older byte-code but that never ever worked out.

I would still like to see a solution using ```java.version``` as this is the convenience way to do it also used in ```spring-boot-starter-parent``` that we will go to extend sooner or later. 

I still do not 100% understand why maven is resolving ```${java.version}``` here. I thought with our current approach only ```^property^```` would be resolved but not ```${property}```. Maybe there is an excuse if the property is a JVM system property what would fully explain the problem and might clash with other system properties as well.

**Comment by sobkowiak** [comment]
Look here https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/spring-boot-starter-parent/pom.xml#L20

`java.version` works in other projects because the projects define this variable in the pom file like here

```xml
<java.version>1.6</java.version>
```

We can still use `java.version` insted of the both variables introduced by me but we must define `java.version`  in our pom

```xml
<java.version>1.7</java.version>
```

**Comment by sobkowiak** [comment]
Ok, I can see now the problem. I have replaced my variables by the `java.version` (defined in the main pom) but the variable defined im pom is not used when replacing the placeholder while resource feltering.

**Comment by sobkowiak** [comment]
As a workaround we can introduce a temporary variable `template.java.version` in tempate pom initialized with the value `java.version` defined in the main pom. We can next use the temporary variable in filtering in the archetype resources. We should next try to check where is the real problem. 

I have started maven build with the debug mode and I can see the variable `java.version` defined in pom is overriden later by the JRE version while filtering.

**Comment by sobkowiak** [comment]
As a workaround we can introduce a temporary variable `template.java.version` in tempate pom initialized with the value `java.version` defined in the main pom. We can next use the temporary variable in filtering in the archetype resources. We should next try to check where is the real problem. 

I have started maven build with the debug mode and I can see the variable `java.version` defined in pom is overriden later by the JRE version while filtering.

**Comment by sobkowiak** [comment]
I have created a separate issue for this problem #263

**Pull request closed without merging**
