### PR TITLE
oasp/oasp4j#207: added example for solution 3 (CSV based test with se…

### PR DESCRIPTION
**Pull request by Max-Goebel**
…renity)

There are some problems with dependencies, so this change should not be accepted without correction. I have just created it in order to discuss advantages and disadvantages of data driven test with serenity.

This are the two problems with the dependencies:
- Guava must be upgraded to version 18.0. I don't know which side effects this may have. Please review and test it.
- A new dependency "xml-apis" must be created. Unfortunately, this dependency causes the AccessControlSchemaXmlValidationTest to fail. I have no idea why and how to fix it.

Furthermore, I think I found a little bug in UcManageOrderPositionImpl and fixed it.

### CODE REVIEW

**Comment by hohwille** [comment]
build error looks like dependency(-management) problem that I can not easily track down with the diffs. In general your PR looks right. So :+1: already for your input.
For the test-cases can you follow our own conventions and use AssertJ assertions instead of JUnit-Standard-Asserts. Simply extends one of the for Base-Classes that we provide for each test-level such as ComponentTest. Further replace TODO with 1-2 sentences JavaDoc what is the goal of the test.
Cool is especially that before your change we were checking ```currentOrderPosition``` against itself.
To see the actual value of serenity it would be nice to observer the reporting if the test fails.
I suppose that this is where it gets interesting. Everything else could IMHO be done with plain JUnit and AssertJ about as simple.

**Comment by Max-Goebel** [comment]
* AssertJ assertions: Done
* Replace TODO: Done
* Build error: Not done. I could not reproduce it. I've just got the failing testcase AccessControlSchemaXmlValidationTest, but there are no build errors.
* Test reports: See ...\oasp4j\oasp4j-samples\oasp4j-sample-core\target\site\serenity

**Comment by hohwille** [comment]
We need some testing guys to have a look. @llaszkie any feedback?
This PR is more than overdue and effort for resolving conflicts, etc. rises if we do not merge for ages.
To me this looks like a nice demonstration of combination testing. However, restaurant sample is going to be deleted soon. How should we proceed?

**Comment by hohwille** [comment]
I have liked this as a task for #632 so we can utilize code from this PR for MTS. As the sample has been deleted, I am going to close this PR as it can not be merged anymore.

**Pull request closed without merging**
