### PR TITLE
#159: created a separation of the drink state from the OrderPosition state

### PR DESCRIPTION
**Pull request by oelsabba**
Added a new field of drinkState within the `OrderPositionEto` to achieve a separate state for Drink. This is just the starting point of achieving the separation of SideDish and Meal too. A consequent modification in the UI is definitely needed.

### CODE REVIEW

**Comment by hohwille** [comment]
I might miss something but just from the diff and changes view there are only commits from @julianmetzler and @hohwille but none from @oelsabba 
I can manually merge this locally and have a more detailed look but so far I can not find any related change...

**Comment by hohwille** [comment]
Also comparing your clone shows no differences:
https://github.com/oelsabba/oasp4j/compare/oasp:develop...develop

Maybe you forgot to push before creating the actual pull request?!?

**Comment by may-bee** [comment]
@hohwille , see the message on top 
"oelsabba wants to merge 13 commits into **master** from **develop**"

you compared develop and develop

**Comment by hohwille** [comment]
This pull request was created wrong (from oasp4j to oasp4j). We fixed this together with a new PR #170.

**Pull request closed without merging**
