### PR TITLE
Fix packages to follow OASP guidelines

### PR DESCRIPTION
**Pull request by hohwille**
As shown with ignored test in #497 various packages in our code do not follow own OASP guidelines. This PR fixes various of these packages.

### CODE REVIEW

**Comment by jomora** [comment]
I ran the build locally and separately for each commit and it fails for the last two commits:
- [c3bc712](https://github.com/oasp/oasp4j/pull/498/commits/c3bc712ce03e6bcc2fca589e5c9a2aa0beb77d6e)
- [24b39e6](https://github.com/oasp/oasp4j/pull/498/commits/24b39e6e4863905c3f5c45ce6c61feca315d29f7)

I used the command `mvn clean install`.

Since Travis provides the same error log I don't provide mine here.
However, the following listing shows the first error that occurred during the build.  
```txt
[INFO] [ERROR] COMPILATION ERROR : 

[INFO] [INFO] -------------------------------------------------------------

[INFO] [ERROR] /home/travis/build/oasp/oasp4j/templates/server/target/test-classes/projects/enterprise/project/enterprise/core/src/test/java/it/pkg/general/common/api/builders/BillEntityBuilder.java:[6,42] cannot find symbol

[INFO]   symbol:   class Money

[INFO]   location: package it.pkg.general.common.api.datatype

[INFO] [ERROR] /home/travis/build/oasp/oasp4j/templates/server/target/test-classes/projects/enterprise/project/enterprise/core/src/test/java/it/pkg/general/common/api/builders/BillEntityBuilder.java:[7,45] package it.pkg.salesmanagement.dataaccess.api does not exist

[INFO] [ERROR] /home/travis/build/oasp/oasp4j/templates/server/target/test-classes/projects/enterprise/project/enterprise/core/src/test/java/it/pkg/general/common/api/builders/BillEntityBuilder.java:[8,45] package it.pkg.salesmanagement.dataaccess.api does not exist
```

We faced a similar problem [here](https://github.com/oasp/oasp4j/pull/449), but I've not enough knowledge about CobiGen. Hence, I can't  provide a solution.

**Comment by maybeec** [comment]
I merge #497. You may want to update this PR branch to the latest changes. This may resolve issues as well as merge conflicts.

**Comment by kiran-vadla** [comment]
@jamora, Just to remind on this PR.

**Comment by kiran-vadla** [comment]
@hohwille ,

Regarding the pull request #498 , I have pulled code from your branch fixPackages and merged the code from the branch develop-2.2.0 to it and executed ‘mvn clean install’ . After I executed this command ,  I am receiving lot of compilation errors. I have setup a Skype meeting to discuss these errors at 9 AM CET . If you are not available at this time , please propose another time . Attached are the errors. 

Note : I had to comment import statement ‘import io.oasp.gastronomy.restaurant.general.configuration.BaseWebSecurityConfig;’ in the class ‘io.oasp.gastronomy.restaurant.general.common.impl.security. BaseUserDetailsService’ before executing ‘mvn clean install’

Thanks&Regards,
Kiran.

**Comment by jomora** [comment]
I close this PR since it is handled by #520. 

For any further discussion, please refer to #520!!!

**Pull request closed without merging**
