### PR TITLE
i18n support #245

### PR DESCRIPTION
**Pull request by dsanche2**
i18n support #245

### CODE REVIEW

**Comment by hohwille** [comment]
Marek did a review and had many concerns on this but had no time and missed to give feedback here. Also I see that spring offers most of this in even a better way and we reinvented the wheel here.

Some "nice to have" feedbacks:

* ```Locale``` is an immutable datatype and LocaleDozerFactory is not required. Instead it should be just configured as ```copy-by-reference```.
* Also we should create an AttributeConverter for Locale so we can use Locale in a JPA mapped property.

**Comment by hohwille** [comment]
Do not get me wrong: I very much appreciate the contribution but we a concerned to release it in this state and think about taking it out as we will break APIs if we refactor it later on and it might already be used. It is always easier if we have it in the sample and the app-template where we can change without breaking APIs while if we are providing framework code I want to have stable APIs that we all agree on.

**Comment by hohwille** [comment]
I reverted for the current release and hope not to have offended anybody. We will checky pick several changes from the origianl PR into 1.5.0.
To not cause confusion in release notes, I change the milestone here to 1.5.0.

**Comment by mmatczak** [comment]
I have reviewed both the Wiki page and the code. I think the overall idea on how to support the i18n topic is good and is very similar to what the Spring framework recommends. But the thing is that the Spring framework also provides some abstraction (Java interfaces) as well as default implementation which in many cases is good enough. Of course the implementation can easy be replaced or augmented as needed. I think we should stick to the abstraction and provide some extension points if necessary.

David, please consider using the following Spring abstractions (interfaces):
1. org.springframework.web.servlet.LocaleResolver – we should implement this interface and provide our strategy for getting the locale. The bean should be then registered in the Spring context und the name DispatcherServlet.LOCALE_RESOLVER_BEAN_NAME. The current locale can be obtained from the LocaleContextHolder
2. org.springframework.context.i18n.MessageSource – using this abstraction we can get internationalized messages. Typically ResourceBundleMessageSource or ReloadableResourceBundleMessageSource implementations are good enough.

**Comment by hohwille** [comment]
For 2. I still recommend my solution:
http://m-m-m.sourceforge.net/apidocs/net/sf/mmm/util/nls/api/package-summary.html#documentation

Has someone seriously worked with MessageFormat in a large i18n context?
Have you worked successfully with ChoiceFormat?
Did you never have the problem of I18N messages composed of smaller I18N messages?
Did you have localizers deal with l10N of messages with many parameters named 0, 1, 2, 3, and 4 understanding what is going on?
Did you talk to localizers dealing with ISO-8859-1 and unicode escaped characters what is for some insane reason that standard in Java?
I made a lot of experience and there is a really large gap in MessageFormat. Please have a look at my proposal and then give arguments for or against it.

**Comment by hohwille** [comment]
You can already read the examples from JavaDoc of MessageFormat to see why it sucks:
docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html

> int planet = 7;
 String event = "a disturbance in the Force";
 String result = MessageFormat.format(
     "At {1,time} on {1,date}, there was {2} on planet {0,number,integer}.",
     planet, new Date(), event);

So how would you rewrite this code so that also the event can be localized?
```MessageFormat``` is way too limited and all is solved with ```NlsMessage```.

**Comment by amarinso** [comment]
Maybe is that in our experience we haven't had too much trouble with using simple property files for messages.

I think NlsMessage is a clever solution nonetheless I have some considerations:

- More complex solution than the common property files approach.
- There is an asymmetry between the "default" language being written in Java code and the alternative languages in property files. (Maybe there can be only properties and no default in Java code?).
- It is more complicated to compare between languages to look for missing keys.
- Repetition of the "named" parameters. You have to keep in sync in the message, the annotation and the method parameter (with Java <1.8 at least and no scrambled code)
- Can be the property files be reloaded upon change? sometimes is a requirement and to have the property files on the classpath outside the WAR file.
- `NlsAccess.getBundleFactory().createBundle` seems quite cumbersome to instantiate a bundle. (Maybe it could be instantiated by spring and could be directly injected for usage on other objects.)
- Also `static getBundleFactory()` can be a challenge for testing... or maybe not. I can not tell not having using it.
- Where to put bundles classes and property files?. We should recommend one way to do it on an OASP application. Maybe there is a Global NlsBundle for the entire application? per module?

Maybe we can get more feedback or experience from people using it.

**Comment by amarinso** [comment]
@hohwille Can you provide the NlsBundle solution for your MessageFormat example? 

thanks!

**Comment by hohwille** [comment]
> There is an asymmetry between the "default" language being written in Java code and the alternative languages in property files. (Maybe there can be only properties and no default in Java code?).

This is technically possible but the entire idea of the solution is to ensure that a message can always be resolved at least in root locale / default language as it is bundled in the code in a type-safe way.
The problem of resource bundles is that you have *.properties files and code with keys referencing these properties but mistakes are only revealed at runtime and not at compile time.

> It is more complicated to compare between languages to look for missing keys.

You need to try the solution. There is a tool called ResourceBundleSynchronizer that does this automatically for you. It will add all missing keys with ```TODO <locale>``` and the original message from the code to be translated.
http://m-m-m.sourceforge.net/apidocs/net/sf/mmm/util/nls/base/ResourceBundleSynchronizer.html

> Repetition of the "named" parameters. You have to keep in sync in the message, the annotation and the method parameter (with Java <1.8 at least and no scrambled code)

If you prefer using {0}, {1}, {2} you do not need @Named. So it is just an option. However I never had to rename a parameter so there is no effort keeping this in sync. It is just effort to setup if you use it. But I prefer it as you understand what {key}, {min} and {max} will mean if you translate the message. However it can get really hard with {0}, {1}, {2}. But like in JPQL you have two options here. This is not a disadvantage but and advantage to have an additional IMHO better option.

> Can be the property files be reloaded upon change? sometimes is a requirement and to have the property files on the classpath outside the WAR file.

Property files are reloaded using standard java ResourceBundle mechanism with an own Control implementation for unicode (UTF-8) encoding support. What ever you can do with plain solution can be done here as well. Everything is decouples with interfaces and you can reimplement and replace pretty much everything. As I am the maintainer of the project I can implement additional demands if you have some. So auto-reloading might be a new feature to consider. However, this is tough for java's internal caching of bundles and for performance...

> NlsAccess.getBundleFactory().createBundle seems quite cumbersome to instantiate a bundle. (Maybe it could be instantiated by spring and could be directly injected for usage on other objects.)

It is all available via Interface and as CDI beans. However, if you study the build in NlsThrowable support for exception there is no other way than a static access. I simply want to be able to do ```new MyI18nException()```. There is no spring context available in the constructor of an exception.

> Also static getBundleFactory() can be a challenge for testing... or maybe not. I can not tell not having using it.

If have a lot of unit tests for it in the project. The thing is that if you need to customize and hook into the solution you need to ensure this is done and registered early on. Then everything works fine and is proven to work. However, if you want to replace components that are statically accessible while the system is running you will end up in concurrency nightmares.

> Where to put bundles classes and property files?. We should recommend one way to do it on an OASP application. Maybe there is a Global NlsBundle for the entire application? per module?

We already have it in our sample and it was there from the start:
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/general/common/api/NlsBundleApplicationRoot.java
It is recommended to have a bundle per module whatever a module is. In case of our sample application there is just one for the entire application and that should be fine. In case your application is way bigger you might want to modularize and have one bundle per module. This discussion is IMHO totally independent. The decision should be the same with NlsMessage or without.

Maybe one day we will also have a GWT channel for OASP (GWT is supported by NlsMessage solution of mmm) or we will have a JavaFx client. Then it might get a lot more challenging and we can really benefit from the power of the solution such as recursive localization, etc. 
Also with ```NlsObject``` you can even create your own custom Enums so they are localizable and can be added as argument to an NlsMessage. Do all that with plain Java resouce bundle and MessageText. As I said before I initially wanted to create an ultra thin wrapper around MessageText but the more experience I gained the more I came to the point that many things of this in Java are really crappy and stepwise replaced more functionality. Still everything is fully compatible - including formats such as date and number format using the original also crappy JDK implementations that are not threadsafe and therefore not reusable and including the totally awkward and crazy escaping syntax of MessageText with ' and { that really sucks but I wanted to fully support what people have been forced to get used to and make it easy to switch from MessageText to NlsMessage.

I hope I brought some arguments why to consider the solution. If you have more concerns or questions feel free to ask.

**Pull request merged**
