### PR TITLE
Reworked archetype/template

### PR DESCRIPTION
**Pull request by hohwille**
I am reworking our maven archetype (project template):
* [x] #628 decouple from restaurant app
* [x] #608 and #613 spring-boot-starter-jdbc
* [x] #392 Tidy up
* [x] #384 modularization
* [x] #374 Batch
* [x] #401 OWASP dependency check
* [x] #632 improve test infrastructure (issue #632 not done but enough for archetype)
* [x] add maven config for sonarqube and jacoco to have projects ready for SonarQube
* [x] add maven license plugin as described below by @MarcoRose 
* [x] include subsystemtests and fix REST-Service test / CXF issue
* [x] complete support for multiple databases (add DDLs/SQL for different DBs, make archetype configurable for specific DB)

This PR is now complete. Still we can discuss to remove BinaryObject but IMHO it is easier to keep this out here and if we want to do that simply create another PR afterwards. Please still see my open issues in the list on the first comment.

### CODE REVIEW

**Comment by hohwille** [comment]
To be honest: our archetype was/is kind of a mess (contains restaurant specific leftovers, code with smells and anti-patterns, etc.). I am still in the process of heavy rework. Contribution and feedback is most welcome.

**Comment by MarcoRose** [comment]
Please add the maven license plugin with some configuration-options.
A user may then manually execute: 
``` 
mvn license:aggregate-download-licenses 
``` 
and
``` 
mvn license:aggregate-add-third-party
``` 
The plugin can also be activated to run during build
```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <version>1.14</version>
        
        <!-- configuration outside of execution-tags will be applied for all calls of license-maven-plugin -->
        <configuration>
          <outputDirectory>${project.build.directory}/generated-resources</outputDirectory>
          <sortArtifactByName>true</sortArtifactByName>
          <includeTransitiveDependencies>true</includeTransitiveDependencies>
          <!-- the "missing file" declares licenses for dependencies that could not be detected automatically -->
          <!-- find the "missing files" in all child-projects at the following location -->
          <!-- if the "missing files" are not yet existing in child-projects they will be created automatically-->
          <useMissingFile>true</useMissingFile>
          <failOnMissing>true</failOnMissing>
          <missingFile>src/license/THIRD-PARTY.properties</missingFile> 
          <overrideFile>src/license/override-THIRD-PARTY.properties</overrideFile>
          <!-- harmonize different ways of writing license names -->
          <licenseMerges>
            <licenseMerge>Apache Software License, Version 2.0|The Apache Software License, Version 2.0</licenseMerge>
            <licenseMerge>Apache Software License, Version 2.0|Apache 2.0</licenseMerge>
            <licenseMerge>Apache Software License, Version 2.0|Apache License, Version 2.0</licenseMerge>
          </licenseMerges>
          <encoding>utf-8</encoding>
        </configuration>

        <!-- 
          In case you want to create license information during regular builds, uncomment below executions, 
          then run mvn package. This will create the THIRD-PARTY.txt and will
          download license files into target folder and create a licenses.xml -->
        <!--
        <executions>
          <execution>
            <id>aggregate-add-third-party</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>aggregate-add-third-party</goal>
            </goals>
          </execution>
          
          <execution>
            <id>aggregate-download-licenses</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>aggregate-download-licenses</goal>
            </goals>
          </execution>          
        </executions> 
        -->
      </plugin>
```
Thank you.

**Comment by hohwille** [comment]
Build broke because spring boot plugin already requires java8. This is actually not so great. Should I upgrade `travis.yml` or do we need to get stuck with old plugins because of Java7 support?

**Comment by hohwille** [comment]
@MarcoRose I have integrated license-maven-plugin. To be honest I can not see a real benefit of this plugin over the already integrated `Project Dependency Management`. What is the real added value of this? Maybe I am missing some features...
It does not seem to judge on used licenses even the normalizing of the licenses is not properly honored. I will check if I messed this by reading the docs (http://www.mojohaus.org/license-maven-plugin/aggregate-third-party-report-mojo.html#licenseMerges) and trying to simplify your given config.

**Comment by hohwille** [comment]
Both
```
        <configuration>
          <licenseMerges>
            <licenseMerge>Apache Software License, Version 2.0|The Apache Software License, Version 2.0</licenseMerge>
            <licenseMerge>Apache Software License, Version 2.0|Apache 2.0</licenseMerge>
            <licenseMerge>Apache Software License, Version 2.0|Apache License, Version 2.0</licenseMerge>
          </licenseMerges>
        </configuration>
```
as well as
```
            <licenseMerges>
              <licenseMerge>Apache Software License, Version 2.0|The Apache Software License, Version 2.0|Apache 2.0|Apache License, Version 2.0</licenseMerge>
            </licenseMerges>
```
Does not have any effect on the report. No matter if I put this into `<configuration>` of `<pluginManagement>` or `<reporting>` for the `license-maven-plugin`.
In any case I get the original licenses listed without normalization. IMHO this plugin is not so much of a benefit but correct me if I am missing some features...

**Comment by hohwille** [comment]
Really time-consuming tasks here...
maven succeeded locally but travis is again causing an error:
> [INFO] [ERROR] Errors: 
[INFO] [ERROR]   SecurityRestServiceImplTest.testGetCurrentUser:75 Â» ServiceInvocationFailed Wh...

**Comment by hohwille** [comment]
So the last thing to finally complete this would be to add DDL SQLs for further DBs:
* [ ] h2
* [ ] postgresql
* [ ] oracle
* [ ] mysql/mariadb
* [ ] hana

**Comment by vapadwal** [comment]
While testing project creation via project template using eclipse found below issues:
1. While creating project via eclipse, its giving below error 

Required property "dbType" is not set.

Here we have to manually put the value then only its working.  it should take the default value i.e h2 in this case.


2. Project creation was successfull with dbTyoe put as h2, but when run SpringBootApp class(main class) to start server got below exception:

Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'security' cannot be found on object of type 'org.springframework.beans.factory.config.BeanExpressionContext' - maybe not public?

In BaseWebSecurityConfig.java 
@Value("#[[$]]#{security.cors.enabled}")
Updated it with below :
@Value("${security.cors.enabled}")

With this it was able to pick the value from application.properties, with this it was able to run the server.

**Comment by hohwille** [comment]
@vapadwal Thanks for your valuable feedback. Seems I still missed some things out. Actually I left no default for `dbType` as in my case I was then prompted for it, while otherwise you are not even aware that such a property even exists. However, I am also fine to add `h2` as simple default and instead add some additional docu and maybe also something to devcon later.

For the wrong velocity expression I have to fix asap. I guess I will have to scan all templates for such expressions to verify there is nothing else I missed. This is definitely a stupid bug I missed out. Great that you found it.
Thanks :+1: I will update my fork and this PR very soon.

**Comment by hohwille** [comment]
I have fixed most of the issues locally (sorry for the delay - too busy with other projects).
However I am still struggling with velocity messing up with javadoc link syntax as it tries to parse `#link` as a marco and then fails on subsequent syntax.
* We are using maven-archetype-plugin in version 3.0.1: https://github.com/hohwille/oasp4j/blob/feature-template/pom.xml#L39
* This plugin version is using velocity in version 1.7: https://maven.apache.org/archetype/maven-archetype-plugin/dependency-management.html
* According to velocity 1.7 documentation we should be able to escape entire blocks with `#[[` and `]]#`: http://velocity.apache.org/engine/1.7/vtl-reference.html#unparsed-content

However the latter is not working. Therefore it seems that we still need to keep this ugly 
```
#set( $symbol_pound = '#' )
```
and replace all `#` signs with `${symbol_pound}` what is kind of ugly.

**Comment by hohwille** [comment]
So I am done with this and resolved all outstanding remarks and problems.
Still I see further room for improvement but as that depends on other PRs (e.g. https://github.com/oasp/oasp4j/pull/631) I want to keep that out of this PR.

**Comment by vapadwal** [comment]
While testing templates below are some more issues that are encountered

1. while testing with different databases, below code in application.properties(/oasp4j-template-server/src/main/resources/archetype-resources/core/src/main/resources/application.properties) always creates db/type/mysql for all the databases. 

#if ($dbType != 'mariadb')
flyway.locations=classpath:db/migration,classpath:db/type/mysql
#else
flyway.locations=classpath:db/migration,classpath:db/type/${dbType}
#end

When tested it with $dbType == 'mariadb' it gives correct classpath for all the databases

2. while testing it for oracle database, had to put size and data in quotes. Also the value for data need to be shorten as oracle was not allowing to insert more than 4000 character string in a column.
File Name : V0004__Add_blob_data.sql
INSERT INTO BinaryObject( ID,MODIFICATIONCOUNTER,"size","data",MIMETYPE) VALUES (10, 0,72861, '..........','image/png');

3. Also while testing it with oracle after all the above issue fixed got the below exception. It was not able to validate the schema. but with other database like mysql and postgre the schema validation did not threw this error.

Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [data] in table [BinaryObject]
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateTable(SchemaValidatorImpl.java:85) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]

worked when commented spring.jpa.hibernate.ddl-auto=validate

**Comment by hohwille** [comment]
> `if ($dbType != 'mariadb')`

OMG. Stupid me! Excellent finding. Will fix that asap. Why didnt the tests reveal that? Guess they are lacking assertions...

**Comment by hohwille** [comment]
@vapadwal thanks for pointing this out. Shame on me - really obvious. I was blind (mainly too busy with other projects) but somehow also my search seems not to work as I searched for `$dbType != 'mariadb'` with no hits. Maybe some regex interference - whatever.
You are completely right. These are stupid mistakes and I will fix them asap.

After that I will try to test this with local oracle XE and see if I can reproduce and maybe also fix the strange exception. Otherwise I would propose to file an issue for that and get this merged anyhow. It was worse before and neither working with Oracle without PR so we still only improve quality here.

**Comment by hohwille** [comment]
Okay. It gets even more messy. While Oracle seems to require quotes in the column names other DBs like h2 do not even support quoting column names as they treat the quote as part of the column name and not as a kind of escape.

**Comment by hohwille** [comment]
Okay. If further improved the oracle config according to:
https://blogs.oracle.com/dev2dev/get-oracle-jdbc-drivers-and-ucp-from-oracle-maven-repository-without-ides
(see also https://github.com/oasp/my-thai-star/pull/71).

**Comment by hohwille** [comment]
I can instantiate and run the archetype with oracle but booting the spring boot app leads to the same error that @vapadwal was stating.
Oracle is simply too limited to insert the BLOB this way:
https://stackoverflow.com/questions/13945710/error-ora-01704-string-literal-too-long

The workarounds would maybe fix this for oracle but again break it for other DBs. The easiest fix for now would be to simply put only a small BLOB (picture) in our masterdata SQL. Or as an alternative and as questioned from the start remove the entire BLOB stuff including all its code from the archetype.
I guess a regular user expects to get an empty application rather than a little demo how to manage BLOBs via REST API. For the moment and to finalize this PR (it has really a very long and bloody history) I would prefer to simply replace the BLOB value with something small that works in oracle and then finally complete this PR first by merging it.
Then we are free for another PR or issue about removing the BLOB stuff from archetype once more.

**Comment by hohwille** [comment]
I was able to replace the BLOB with something smaller that is now working with oracle.
However, next I get this error from oracle:
```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [timestamp] in table [RevInfo]
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateTable(SchemaValidatorImpl.java:85) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.doValidation(SchemaValidatorImpl.java:50) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:91) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:475) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]
	... 22 common frames omitted
```
Actually the column `timestamp` is present in `RevInfo` but there is again some reserved keyword issue that we are facing here. Never ending story though...

**Comment by hohwille** [comment]
Okay. Works with oracle if we put the column name in quotes: @Column("\"timestamp\")
I hope this does not break the mapping for other DB types.

**Comment by hohwille** [comment]
Build and tests worked locally with maven. No idea why it fails with travis now. This PR is really driving me nuts.

**Comment by vapadwal** [comment]
I have test with the new changes again and below are some more issues found

Issue 1: 

Getting below exception when executed mvn install against oasp4j

_apableBeanFactory.java:1624)
        ... 90 common frames omitted
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [timestamp] in table [RevInfo]
        at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateTable(SchemaValidatorImpl.java:85)
        at 
        ... 96 common frames omitted
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.498 s - in io.oasp.gastronomy.restaurant.tablemanagement.service.impl.rest.TablemanagementRestServiceTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SecurityRestServiceImplTest.testGetCsrfToken » IllegalState Failed to load App...
[ERROR]   SecurityRestServiceImplTest.testGetCurrentUser » IllegalState Failed to load A...
[ERROR]   SecurityRestServiceImplTest.testLogin » IllegalState Failed to load Applicatio...
[ERROR]   TablemanagementWebServiceTest.testWebService » IllegalState Failed to load App...
[INFO]
[ERROR] Tests run: 43, Failures: 0, Errors: 4, Skipped: 1
[INFO]_

I think we need timestamp in quotes. refer to below file

https://github.com/hohwille/oasp4j/blob/feature-template/samples/core/src/test/resources/db/tablemanagement/V0001__R001_Create_schema.sql#L134


Issue 2:

Created a project in h2 and oracle got the below error both in h2 and oracle

_Caused by: org.hibernate.DuplicateMappingException: Table [RevInfo] contains logical column name [timestamp] referring to multiple physical column names: ["timestamp"], [timestamp]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl$TableColumnNameBinding.bindLogicalToPhysical(InFlightMetadataCollectorImpl.java:902) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]_

Because of the above issue I am not able to test further.	
	
Issue 3 :

The project get created via console but when tried it creating via eclipse got the below error

_Unable to create project from archetype [io.oasp.java.templates:oasp4j-template-server:3.0.0-SNAPSHOT]
org.apache.maven.archetype.exception.ArchetypeGenerationFailure: Error merging velocity templates: Lexical error: org.apache.velocity.runtime.parser.TokenMgrError: Lexical error at line 31, column 4.  Encountered: <EOF> after : ""_

Might be because of below

https://github.com/hohwille/oasp4j/blob/feature-template/templates/server/src/main/resources/archetype-resources/__batch__/src/test/java/__packageInPathFormat__/general/common/base/test/TestUtil.java#L31
or
https://github.com/hohwille/oasp4j/blob/feature-template/templates/server/src/main/resources/archetype-resources/core/src/test/java/__packageInPathFormat__/general/common/base/test/TestUtil.java#L31

**Comment by hohwille** [comment]
@vapadwal thanks for testing and your feedback.
I fixed Issue 1. I already fixed the same issue in the template but did not hit it before with the sample. Further as you can verify the travis build of my change was also green so something is rather strange or evil here.

For issue 2 I have the opposite effect. It did not work without the quotes and therefore I did all the changes. I can test everything locally with OracleXE and it is working in my case. So maybe it works with my OralceXE version (11.2.0) but not with yours. In that case I rather have to give up for the moment. To repeat myself I just tried to pick up what @kiran-vadla once did here and it also worked perfectly for my local OracleXE. I am not sure how we should handle such cases in general but our problem somehow is that we have a buggy and crappy template currently but creating a PR to improve requires ultimate perfection and takes months or years. I guess most other contributors would have given up with their PR way before. So I guess I should also take the chance to open a community discussion outside this PR about how we want to work in such cases in the future. Maybe it is better to finally accept and merge PRs and rather open a follow up issue for further improvements than getting stuck so badly. Do not get me wrong here: Your feedback is valuable, perfect and helps to improve quality. Also I really messed up some things that you digged out and it is great that we fixed this before projects ran into the issue.

For issue 3 I am also a little bit puzzled but IMHO this is as following:
I upgraded the archetype plugin so we now have a newer velocity engine under the hood for our archetype that provides features to better deal with nasty escaping, etc. However, when instantiating the archetype under some circumstances maven uses an older version of the archetype plugin with an older version of velocity that then can not parse our templates resulting in that error.
This is good to know, but next we would need to understand under which circumstances this will happen. * Is it due to an older version of maven (can you please provide the output of `mvn -v` and check a recent maven version). 
* Does it depend on the versions of maven archetype plugin available in your local repo?

So to make things clear: This error does not happen when I test it. My environment:
```
mvn -v
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: D:\Projekte\oasp\software\maven\bin\..
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: D:\Projekte\oasp\software\java\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```
My invocation to create the project was e.g.:
```
mvn archetype:generate -DarchetypeGroupId=io.oasp.java.templates -DarchetypeArtifactId=oasp4j-template-server -DarchetypeVersion=3.0.0-SNAPSHOT -DgroupId=com.company -DartifactId=demo -Dversion=1.0.0-SNAPSHOT -DdbType=oracle -Dbatch=batch
```

**Comment by hohwille** [comment]
IMHO the remaining question is if that trick/workaround/hack is actually evil:
https://github.com/oasp/oasp4j/pull/629/commits/537740f528b0b173352762daaf4755f8847933f9

If yes - what is the alternative to make this work with all the different databases. SQL aims to be a standard but actually it is not and is rather a pain.

**Comment by vapadwal** [comment]
For issue 3, i.e. velocity issue:
The problem is not with project creation via mvn command , but its when we create project via eclipse wizard(File>New>Maven Project)

For " what is the alternative to make this work with all the different databases "
If its possible, I think its better to rename the timestamp column just the way we did it for "size".

**Comment by hohwille** [comment]
> For timestamp Issue " what is the alternative to make this work with all the different databases "
> If its possible, I think its better to rename the timestamp column just the way we did it for "size".

I agree that we should not use reserved keywords. However, this big issue here is that projects are already actively using this code and would then be forced to update their DBs in production. I do not see this as a good option right now - IMHO we would make some of our users mad and they might go away from Devon/OASP then... WDYT?

**Comment by hohwille** [comment]
@vapadwal thanks for your patience and continuous testing and reviewing this PR. It might have been tedious but I hope we now finally got it well!

> I am also able to create project successfully via mvn command line, but the issue is happening with me when trying to create project via eclipse wizard(File>New>Maven Project)

I fixed this be stop using this advanced velocity feature and simply kick out the javadoc link that caused velocity to fail.

> Now with this changes all the timestamp issue will be fixed.

I also fixed this last occurrence. I missed it because it is not used by the tests but "only" if you actually run the archetype project with h2 what I never properly tested in the hurry. Thanks for your excellent quality assurance!

**Comment by hohwille** [comment]
Fine now we have a technical travis issue:
```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find io.oasp.java:oasp4j-bom:pom:3.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced
```

**Comment by vapadwal** [comment]
I am working on issue(https://github.com/oasp/oasp4j/issues/599), as it is related to PR 629 I have put the question over here.

Here the project that is created using oasp4j uses Java 1.8.

The issue(for details of the issue please refer to https://github.com/oasp/oasp4j/issues/599) here is that we are getting exception when we change from Java 1.7 to Java 1.8, below is the exception that we are getting.

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)

We are getting this issue as Java 1.8 was not compatible with asm 4.2 dependency that has been used in application. I have tested it by updating the cglib from 3.1 to 3.2.4, as asm dependency is transitive to cglib, it had download asm 5.1 dependency and this had solved the problem

The change required here will be to update the cglib version from 3.1 to 3.2.4 in the bom (oasp4j/bom/pom.xml). 

Now question here will be, should we include this change in PR 629, as mentioned in this yammer thread that we will support Java 1.8 in PR 629. Also other than cglib change we required to update the pom to support java 1.8
https://www.yammer.com/capgemini.com/#/Threads/show?threadId=1072713514

**Comment by AbhayChandel** [comment]
Tested the PR and works fine.

**Pull request merged**
