### PR TITLE
 Fixed Fylway 4.2.0 upgrade for restaurant bootified war

### PR DESCRIPTION
**Pull request by AbhayChandel**

### CODE REVIEW

**Comment by AbhayChandel** [comment]
Issue #654 is also fixed under this PR.

**Comment by vapadwal** [comment]
@hohwille below might be reason for the travis error. Sonatype no longer supports TLSv1.1 and below

https://stackoverflow.com/questions/50946420/could-not-transfer-artifact-https-repo-maven-apache-org-maven2-received-fat

**Comment by hohwille** [comment]
> below might be reason for the travis error. Sonatype no longer supports TLSv1.1 and below

@AbhayChandel exactly the right observation. That is what I was discussing on Yammer and what I already workaround with this hack somewhere:
https://github.com/oasp/oasp4j/pull/651/commits/6b2be5ee4edf6d7440c762138bf56836cbbad72a

This is indeed an ugly workaround but you might give it a try unless a better fix is available.

**Comment by vapadwal** [comment]
This PR is tested and we can merge now

**Pull request merged**
