### PR TITLE
 replace Criteria API with dynamic queries using QueryDSL #220 

### PR DESCRIPTION
**Pull request by cmammado**
This is a new pull request for the issue with the Criteria API. So the Criteria API replaced with the Querydsl in io.oasp.gastronomy.restaurant.offermanagement.dataaccess.impl.dao.OfferDaoImpl. A new Test OfferManagementTest.java is added. There was no problem with line end formatting. The problem was that I have deleted the OfferDaoImpl.java and created it again. That is why not only the changes I have made with Querydsl, but the whole class OfferDaoImpl was shown as a new addition. Now only the changes I have made with Querydsl are visible.

### CODE REVIEW

**Comment by cmammado** [comment]
Checks have failed. If I look at the details, so I see that the new test in OfferManagementTest.java fails. I dont know why it fails here. If I run this test in Eclipse, it does not fail.

**Comment by MarcoRose** [comment]
Travis test execution answered: 

Failed tests: 
OfferManagementTest.testFindOffersFiltered:66 expected:<0> but was:<3>

**Comment by cmammado** [comment]
I have already seen "expected:<0> but was:<3>" in details. But I dont know why this happens. Because in Eclipse the test passes successfully. I also saw that it was made some changes in test infastructure. Maybe this problem relates to these new changes. It would be very helpful if I get a feedback on this. Thanks in advance.

**Comment by cmammado** [comment]
I dont know why, but all checks have successfully passed now. And the branch has no conflicts with the base branch.

**Comment by maihacke** [comment]
There are some changes needed to the pom.xml:
- Versionnumbers should go to the oasp4j-bom. Querydsl is already there but with an older version.
- querydsl-apt is not necessary and should not be included
- why is the slf4j-log4j bridged includes? is querydsl the first library which requires this? If so please include versions in the bom and not in the pom.

**Comment by maihacke** [comment]
Code looks good, here are a few minor points we should change

- Why is OfferDao#findOffersFilteres deprecated?
- We should use a static import for Alias.$ for better readability (maybe we should even change the ide config to automate this (favorite imports))

**Comment by hohwille** [comment]
> Why is OfferDao#findOffersFilteres deprecated?
IMHO because it is superseded by findOffers(OfferSearchCriteriaTo). As it still used up to the REST-service is has been deprecated. The client has to be changed not to use this any more and then it can be removed.

**Comment by maihacke** [comment]
Okay, then @cmammado please add an short comment.

**Comment by MarcoRose** [comment]
Chinara went back to study and is not available. We can finalize ourselves. I will implement the static import.

I strongly suggest not to remove the method, even if not used by the client, because it is our only showcase for a more complex usage of QueryDSL. Am I wrong?

**Comment by hohwille** [comment]
> I strongly suggest not to remove the method, even if not used by the client, because it is our only showcase for a more complex usage of QueryDSL. Am I wrong?

```findOffers(OfferSearchCriteriaTo)``` is the method with "complex" usage of QueryDSL. I would rather call it beyond trivial but not complex...
```OfferDao.findOffersFilteres``` is using Criteria API and shall be deleted.

**Comment by MarcoRose** [comment]
I said "more complex", which doesn't necessarily mean "complex". If I say "the car is cheaper", the car can still cost a 100k€.

In this PR OfferDao.findOffersFiltered now uses QueryDSL and it contains server side sorting as a showcase (the only place), so it might be useful to keep it, even though client doesn't use it. We should make a decision, in what component we want to have a good example of using QueryDSL. If it is the offermanagement, we should keep the method (besides, I would be sorry Chinara spent the effort for throwing it out).

**Comment by hohwille** [comment]
Can someone summarise what is left here? Or are we now ready to accept this PR?
I lost track after all comments...
If there are open issues please add a comment with the list of these aspects to improve.
Otherwise we could accept the PR (or do a final review).

**Comment by hohwille** [comment]
If I do not get further feedback, I will do a rough review once more and merge this in the next days...

**Comment by MarcoRose** [comment]
I propose to keep one of the deprecated search-methods (OfferDao.findOffersFiltered ) including server-side sorting and to remove the deprecated-annotation even if no client is using it right now. I guess it shows a bit more of the QueryDSL-usage than the generated search methods.

**Comment by maihacke** [comment]
If Marco did the static imports the code should be fine. The last open point is what we are going to do with the deprecated find method. I could live with @MarcoRose suggestion and just remove the deprecation flag. Maybe we could add a comment that this method is not used and just there to demonstrate querydsl usage.

**Comment by maihacke** [comment]
see PR #411

**Pull request closed without merging**
